# baseURL: localhost:8080
baseURL: https://davidstreet.org/hugo2/
# baseURL: http://davidstreet.org/
languageCode: en-gb
title: "Tokyo Adachi Roshukai UK"

font: https://fonts.googleapis.com/css?family=Source+Code+Pro|Roboto:400,700
theme: hugo-tailwind-journal
pygmentsCodeFences: true
pygmentsUseClasses: true


params:
  color: black           # Any color in CSS syntax
  width: 48rem          # Any length in CSS syntax

  # Define which content types are shown on the homepage
  mainSections: dojo

  mon:
      src: /hugo2/img/Honda-mon-1200.png
      # src: honda-1.png
      shape: ""
      width: ""
      alt: "Honda mon"

  kanji: 蘆洲会

  footer: Except where otherwise noted, content on this site is licensed under a
    a <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">
    Creative Commons Attribution 4.0 International License</a>.
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.

  summaries: false      # Set to true to show summaries of posts on homepage
  divider: '\2015\2015' # Set to false to remove divider below posts on homepage
  schema: false         # Set to true to add Schema.org metadata
  opengraph: false      # Set to true to add Open Graph metadata
  twittercards: false   # Set to true to add Twitter Cards metadata
  utterances:
    repo:               # Set to Utterances repo URL to add Utterances comments
    issueterm: pathname
    theme: github-light
  netlify:
    honeypot: false     # Set to true to add honeypot field in contact form
    recaptcha: false    # Set to true to add recaptcha challenge in contact form
  # css:                # Uncomment to add custom CSS from a list of files
  #   - css/foo.css
  #   - bar.css
  # js:                 # Uncomment to add custom JS from a list of files
  #   - js/foo.js
  #   - bar.js


# menu:
#   nav:
#   - name: About
#     url: about/
#     weight: 1
#   - name: Dojo
#     url: dojo/
#     weight: 2
  # - name: Tags
  #   url: tags/
  #   weight: 3
  # - name: Categories
  #   url: categories/
  #   weight: 4
  # - name: RSS
  #   url: index.xml
  #   weight: 5
